dataset: 11k
aspect: dorsal_r
model: vitb16
n_ctx: 4

batch_size: 32
epochs: 1
lr: 0.0001
loss: [cross_entropy, triplet]

prompt_ckpt: saved_models/clipreid_prompts_vitb16_11k_dorsal_r.pth
save_path: saved_models/clipreid_vitb16_img_encoder_ft_11k_dorsal_r.pth
log_path: train_logs/clipreid_vitb16_img_encoder_ft_11k_dorsal_r.log
