experiment: eval_stage1_frozen_text

dataset: 11k
aspect: dorsal_r
model: rn50
variant: stage1_frozen_text

batch_size: 32
num_workers: 4

 # this model is the best model found rather than best since it is calculating best based on the reid accuracy
model_path: saved_models/stage1_frozen_text_rn50_11k_dorsal_r_prompt_nctxNA_e7_lr1e-05_bs32_FINAL.pth


output_dir: eval_logs/
