# === General Experiment Info ===
experiment: stage3_promptsg
dataset: 11k
aspect: dorsal_r
model: vitb16
variant: promptsg
stage: stage3_promptsg

# === CLIP Model Config ===
clip_model:  vitb16
pretrained: true
freeze_text_encoder: true

# === Textual Inversion (Pseudo-token) ===
pseudo_token_dim: 512
pseudo_token_init: random

# === Multimodal Interaction Module ===
cross_attention_layers: 1
transformer_layers: 3
attention_heads: 8

# === Prompt Configuration ===
use_composed_prompt: true
#prompt_template: "A detailed photo of {aspect} hand for identification." -- for all
#prompt_template: "A biometric scan of the {aspect} hand for ID verification."
prompt_template: "A captured frame showing a persons {aspect} hand during surveillance."
#prompt_template: "Label: {aspect} hand, individual ID for re-identification."


# === Training Config ===
batch_size: 32
epochs: 60

early_stop_patience: 10

lr_clip_visual: 0.000002
lr_modules: 0.000002
weight_decay: 0.0005
supcon_loss_weight: 0
loss_tri_weight: 1.0
loss_id_weight: 0.2

# === Dataloader Settings ===
num_workers: 4
shuffle: true
pin_memory: true

#classifier: linear # arcface is not improving the result
classifier: arcface
bnneck_reduction: true
bnneck_dim: 256
val_type: reid  # optional: prevent CE-style val logic


# === Logging and Checkpoint Saving ===
output_dir: train_logs/
save_dir: saved_models/
save_frequency: 10
log_frequency: 50

# === Resume and Checkpoints ===
resume_from_checkpoint: null
