dataset: 11k
aspect: dorsal_l
model: rn50
variant: stage1_frozen_text

epochs: 1
batch_size: 32
lr: 0.0001
loss: cross_entropy

save_path: saved_models/stage1_rn50_11k_dorsal_l.pth
log_path: train_logs/stage1_rn50_11k_dorsal_l.log
