# === PromptSG Evaluation Config for Stage 3 ===
experiment: eval_stage3_promptsg

dataset: 11k
aspect: dorsal_r
model: rn50
variant: promptsg

batch_size: 32
num_workers: 4

# Path to the best trained model from Stage 3 (PromptSG)
model_path: saved_models/stage3_promptsg_rn50_11k_dorsal_r_promptsg_e20_lrNA_bs32_BEST.pth

# Where to save the split-wise and average evaluation metrics
output_dir: eval_logs/
