dataset: 11k
aspect: dorsal_r
model: vitb16
variant: stage2_loss_ce_triplet

epochs: 1
batch_size: 32
lr: 0.0001
loss: [cross_entropy, triplet]

save_path: saved_models/stage2_vitb16_11k_dorsal_r_ce_triplet.pth
log_path: train_logs/stage2_vitb16_11k_dorsal_r_ce_triplet.log
