experiment: validate_stage2a_prompt_vitb16_11k_dorsal_r
dataset: 11k
aspect: dorsal_r
model: vitb16
variant: clipid

# Prompt config  must match what was trained
n_ctx: 8
ctx_init: "a hand"
prompt_template: "A photo of {}'s {aspect} hand for identification."

# Validation setup
batch_size: 32
val_split: ./datasets/11khands/train_val_test_split_dorsal_r/val

# Path to the trained prompt model from Stage 2a
stage2a_ckpt: saved_models/stage2a_prompt_vitb16_11k_dorsal_r_vitb16_11k_dorsal_r_e30_lr1e-04_bs32_ctx8_freezeTrue.pth
