experiment: validate_stage2a_prompt_vitb16_11k_dorsal_r_trainset
dataset: 11k
aspect: dorsal_r
model: vitb16
variant: clipid

# Prompt config — must match training config exactly
n_ctx: 8
ctx_init: "a hand"
prompt_template: "A photo of {}'s {aspect} hand for identification."

# Evaluation on training set
batch_size: 32
val_split: ./datasets/11khands/train_val_test_split_dorsal_r/train

# Path to trained Stage 2a prompt model
stage2a_ckpt: saved_models/stage2a_prompt_vitb16_11k_dorsal_r_vitb16_11k_dorsal_r_nctx8_e30_lr0001_bs32_ctxahand.pth
