experiment: stage1_frozen_text

dataset: 11k
aspect: dorsal_r
model: rn50
variant: stage1_frozen_text


freeze_text: true


epochs: 10
batch_size: 32
lr: 0.00001   # = 1e-5
num_workers: 4
loss: cross_entropy

early_stop_patience: 3


log_dir: train_logs/
save_dir: saved_models/
